"""Sequential MNIST, permuted sequential MNIST and Moving MNIST benchmark."""
import argparse
import json
import os
import time

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader

from temporal_nf import TemporalModel, make_temporal_dataset


def evaluate(model, loader, device):
    model.eval(); correct = total = loss_sum = 0.0
    with torch.no_grad():
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            logits = model(x)
            loss_sum += F.cross_entropy(logits, y).item() * y.numel()
            correct += (logits.argmax(1) == y).sum().item(); total += y.numel()
    return loss_sum / total, correct / total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", choices=["seq", "perm", "moving", "all"], default="all")
    ap.add_argument("--epochs", type=int, default=5)
    ap.add_argument("--subset", type=int, default=5000)
    ap.add_argument("--batch", type=int, default=128)
    ap.add_argument("--lr", type=float, default=3e-3)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--pixelwise", action="store_true",
                    help="use 784 steps instead of 28 row steps")
    ap.add_argument("--data-root", default="data/mnist")
    ap.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    args = ap.parse_args()
    torch.manual_seed(args.seed)
    device = torch.device(args.device)
    tasks = ["seq", "perm", "moving"] if args.task == "all" else [args.task]
    out_dir = "temporal_nf_results"; os.makedirs(out_dir, exist_ok=True)
    all_results = []
    for task in tasks:
        train_ds = make_temporal_dataset(args.data_root, task, args.subset, args.seed)
        test_ds = make_temporal_dataset(args.data_root, task, 0, args.seed)
        train_loader = DataLoader(train_ds, batch_size=args.batch, shuffle=True)
        test_loader = DataLoader(test_ds, batch_size=1024, shuffle=False)
        print(f"\nTASK={task} steps={'784' if args.pixelwise else ('10' if task == 'moving' else '28')}")
        task_results = []
        for kind in ("linear", "relu", "gru", "dynamic"):
            torch.manual_seed(args.seed)
            model = TemporalModel(task, kind, pixelwise=args.pixelwise,
                                  permutation_seed=args.seed).to(device)
            opt = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-4)
            history = []; start = time.process_time()
            for ep in range(args.epochs):
                model.train(); loss_sum = correct = total = 0
                for x, y in train_loader:
                    x, y = x.to(device), y.to(device)
                    logits = model(x); loss = F.cross_entropy(logits, y)
                    opt.zero_grad(set_to_none=True); loss.backward()
                    grad = torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0); opt.step()
                    loss_sum += loss.item() * y.numel(); correct += (logits.argmax(1) == y).sum().item(); total += y.numel()
                te_loss, te_acc = evaluate(model, test_loader, device)
                row = {"epoch": ep + 1, "train_loss": loss_sum / total,
                       "train_acc": correct / total, "test_loss": te_loss,
                       "test_acc": te_acc, "grad_norm": float(grad)}
                history.append(row)
                print(f"{kind:7s} ep{ep+1:02d}/{args.epochs} train={row['train_acc']:.4f} test={te_acc:.4f}")
            result = {"task": task, "model": kind, "history": history,
                      "best_test_acc": max(x["test_acc"] for x in history),
                      "final_test_acc": history[-1]["test_acc"],
                      "parameters": sum(p.numel() for p in model.parameters()),
                      "cpu_seconds": time.process_time() - start}
            if kind == "dynamic":
                result["temporal_diagnostics"] = model.temporal_diagnostics
                # Remove tensors before JSON serialization; the final relation
                # images are intentionally generated by a separate helper.
                model.temporal_diagnostics.pop("last_relations", None)
            task_results.append(result); all_results.append(result)
        with open(os.path.join(out_dir, f"{task}_results_seed{args.seed}.json"), "w", encoding="utf-8") as f:
            json.dump(task_results, f, indent=2, ensure_ascii=False)
    with open(os.path.join(out_dir, f"results_seed{args.seed}.json"), "w", encoding="utf-8") as f:
        json.dump(all_results, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    main()
